# Generated by Django 4.1.7 on 2023-04-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
    ]
